### ISSUE TITLE
striver-sde-sheet

### ISSUE THREAD

**Issue by SHOBHA-0502** [Am10aN16/webD_projects_beginners_Hacktoberfest22#11]
I want to add an array of questions and solutions to the striver sde sheet. which help me a lot during my Microsoft interview.

@Am10aN16 kindly assign this issue to me in hacktober 2022.

**Comment by Ashish93-mrx** [comment]
hello sir,i would like to add a medium level  problem of containing Math+Prefix-Sufix Sum  topic asked in a Amazon interview,please assign me this issue.

**Comment by Am10aN16** [comment]
This  is resolved one but you can create a issue containing your topic and I'll assign that to you.

Thanks
